# don't forget to update config.model
environment: loadTest

app:
  name: champ-admin-auth

server:
  port: 8080
  timeout: 300

log:
  environment: production
  level: info
  format: json

postgres:
  db-name: champ-db
  host: 172.28.240.42
  port: 5432
  pool-size: 30

redis:
  address: 172.28.241.3:6379
  database: 1

email:
  address: peerasateketanun03@gmail.com
  subject: OTP VERIFICATION

user-list-key: USER_LIST_CHAMP





