apiVersion: apps/v1
kind: Deployment
metadata:
  name: champ-admin-auth
  labels:
    app.kubernetes.io/name: champ-admin-auth
    app.kubernetes.io/instance: champ-admin-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: champ-admin-auth
      app.kubernetes.io/instance: champ-admin-auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: champ-admin-auth
        app.kubernetes.io/instance: champ-admin-auth
    spec:
      containers:
        - name: champ-admin-auth
          image: asia.gcr.io/poc-innovation-iot/champ-admin-auth:TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: champ-admin-auth-secret-env
          volumeMounts:
              - mountPath: /config/config.yaml
                name: champ-admin-auth-configmap-file
                subPath: config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 1200m
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 128Mi
      volumes:
        - name: champ-admin-auth-configmap-file
          configMap:
            name: champ-admin-auth-configmap-file